apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard_tp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard_tp
  template:
    metadata:
      labels:
        app: dashboard_tp
    spec:
      containers:
      - name: dash 
        image: sacramento20/dashboard_tp
        imagePullPolicy: Always
        ports:
        - containerPort: 32194