name: ACTIONS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      
      - name: User and Token for Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CLOUD_TP3_USER }}
          password: ${{ secrets.CLOUD_TP3_TOKEN }}
    
      - name: Build and Push image to change Dashboard container
        uses: docker/build-push-action@v4
        with:
          context: task2/dashboard/
          push: true
          tags: sacramento20/dashboard_tp
